baseURL: ''
title: TailblissSite
languageCode: en-us
DefaultContentLanguage: en
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: false
paginate: 9
darkmode_js:
  - assets/js/darkmode.js
enableInlineShortcodes: true

params:
  author: Nusser Studios
  authorimage: ../assets/images/global/author.webp
  og_image: /images/tailbliss-cover.png
  moto: "Visionary Research with Practical Results"
  description: "TSC - The Science Company"
  disable_theme_toggle: false
  disable_stay_uptodate: true

  p1:
    heading: "Our mission"
    image: "images/pages/our-mission.png"
    content:
      - text: ""
      - text: ""
      - text: ""
        
  p2:
    heading: "Services Offered."
    image: ""
    content:
      - text: ""
  p3:
    heading: "Backed by world-renowned investors"
    content:
      - text: ""
    links:
      - text: Meet our investors and advisors
        url: "#"
    logos:
      - identifier: a
        image: "images/global/sample-logo.svg"
        alt: "a"
      - identifier: b
      - identifier: c
      - identifier: d
      - identifier: e
      - identifier: f
  p4:
    heading: "From the blog"
    content:
      - text: ""
  p5:
    heading: "Stay Up to Date"
    content:
      - text: ""
    action: "#"
    label: "Email address"
    placeholder: "Enter your email"
    button: "Notify me"

  social_media:
    github:
      enabled: true
      url: 'https://tscllc.us'
    facebook:
      enabled: true
      url: 'https://tscllc.us'
    instagram:
      enabled: true
      url: 'https://tscllc.us'
    twitter:
      enabled: true
      url: 'https://tscllc.us'

menu:
  main:
    - identifier: prose
      name: Prose
      url: /prose/
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 20
    - identifier: categories
      pre: dropdown
      name: Categories
      weight: 30
    - identifier: dropdown
      pre: complexdropdown
      name: Dropdown
      weight: 40
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 50
  categories:
    - identifier: prose
      name: Prose
      url: /prose/
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 20
  Services:
    - identifier: appearance
      pre: stars # can be stars, comments or piechart
      name: Appearance
      post: "Easy customization"
      url: "#"
      weight: 10
    - identifier: comments
      pre: comments # can be stars, comments or piechart
      name: Comments
      post: "Check your latest comments"
      url: "#"
      weight: 20
    - identifier: analytics
      pre: piechart # can be stars, comments or piechart
      name: Analytics
      post: "Take a look at your statistics"
      url: "#"
      weight: 30
  footer:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: blog
      name: Blog
      url: /categories/blog/
      weight: 20
    - identifier: news
      name: News
      url: /categories/news/
      weight: 30
    - identifier: prose
      name: Prose
      url: /prose/
      weight: 40
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 50

markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: Categories
  tag: Tags

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    enableDNT: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

server:
  headers:
    - for: /**
      values:
        Referrer-Policy: strict-origin-when-cross-origin

module:
  hugoVersion:
    extended: true
    min: "0.104.0"
  imports:
    - path: github.com/nusserstudios/tailbliss
      mounts:
        - source: layouts
          target: layouts
        - source: i18n
          target: i18n
        - source: archetypes
          target: archetypes
        - source: assets
          target: assets
          #excludeFiles: images/* # uncomment for production
        - source: content # comment for production
          target: content # comment for production